apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - ubuntu-22
parameters:
  storage: lvm
  volgroup: openebs
provisioner: local.csi.openebs.io
# volumeBindingMode: WaitForFirstConsumer
